#ifndef LOG_HPP
#define LOG_HPP

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(data);
Q_DECLARE_LOGGING_CATEGORY(interfac);
Q_DECLARE_LOGGING_CATEGORY(interfaceFs);
Q_DECLARE_LOGGING_CATEGORY(interfacePcap);
Q_DECLARE_LOGGING_CATEGORY(interfaceSlp);
Q_DECLARE_LOGGING_CATEGORY(manager);
Q_DECLARE_LOGGING_CATEGORY(packet);
Q_DECLARE_LOGGING_CATEGORY(packetPia);
Q_DECLARE_LOGGING_CATEGORY(crypto);

#endif // LOG_HPP
