#ifndef LOG_HPP
#define LOG_HPP

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(interface)
Q_DECLARE_LOGGING_CATEGORY(interfaceFs)
Q_DECLARE_LOGGING_CATEGORY(manager);
Q_DECLARE_LOGGING_CATEGORY(packet)
Q_DECLARE_LOGGING_CATEGORY(packetBreply)

#endif // LOG_HPP
